export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";

export const FETCH_DATA_PHOTO = "FETCH_DATA_PHOTO";
export const FETCH_DATA_PHOTO_SUCCESS = "FETCH_DATA_PHOTO_SUCCESS";

export const DO_DETAIL = "DO_DETAIL";
export const VIEW_DETAIL = "VIEW_DETAIL";

export const BLOCKING = "BLOCKING";
export const UNBLOCKING = "UNBLOCKING"

export const SEARCH_BOOK = "SEARCH_BOOK";
export const SEARCH_BOOK_COMPLETED = "SEARCH_BOOK_COMPLETED";

export const RESET_STATE = "RESET_STATE";